//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChoThueOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBSC
    {
        public int id_BBSC { get; set; }
        public int idXe { get; set; }
        public int idKH { get; set; }
        public int idNV { get; set; }
        public string MaBBSC { get; set; }
        public string TenSC { get; set; }
        public Nullable<System.DateTime> NgayBBSC { get; set; }
        public string NoiDungSC { get; set; }
        public string TienPhat { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
