//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChoThueOto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public int idHopDong { get; set; }
        public string MaHD { get; set; }
        public Nullable<int> idXe { get; set; }
        public Nullable<int> idKH { get; set; }
        public Nullable<int> idNV { get; set; }
        public Nullable<System.DateTime> NgayHD { get; set; }
        public string NoiDungHD { get; set; }
        public string TienDat { get; set; }
        public string KhuyenMai { get; set; }
        public string GiayToGiuLai { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual Xe Xe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
